export type Project = {
  slug: string
  title: string
  creatorName: string
  creatorUsername: string
  category: string
  duration: string
  views: string
  likes: string
  comments: string
  publishedAt: string
  description: string
  tags: string[]
  status: string
  difficulty: string
  developmentStage: string
  upvotes: string
  bookmarks: string
  thumbnailPath: string
  sourceLinks: {
    label: string
    href: string
  }[]
}

export type Creator = {
  username: string
  name: string
  title: string
  bio: string
  projects: number
  followers: string
  specialty: string
  joinedAt: string
  totalUpvotes: string
  socials: {
    label: string
    href: string
  }[]
}

export type Notification = {
  title: string
  description: string
  time: string
}

export type CurrentUser = {
  name: string
  username: string
  role: string
  avatarFallback: string
  savedProjectSlugs: string[]
  notifications: Notification[]
}

export const feedFilters = [
  "All",
  "AI tools",
  "Web",
  "Mobile",
  "Education",
  "Dev tools",
  "Open Source",
  "Productivity",
]

export const mockCurrentUser: CurrentUser = {
  name: "Peter",
  username: "peter",
  role: "Guest member",
  avatarFallback: "PT",
  savedProjectSlugs: [
    "prompt-harbor",
    "studio-grid",
    "lesson-loom",
    "signal-stack",
    "delta-kit",
    "focus-deck",
    "task-tide",
    "open-lens",
  ],
  notifications: [
    {
      title: "Your saved project updated",
      description: "Prompt Harbor added a new source link and refreshed preview.",
      time: "5m ago",
    },
    {
      title: "Trending project saved",
      description: "Studio Grid was added to your bookmarks earlier today.",
      time: "1h ago",
    },
    {
      title: "New recommendations",
      description: "Three productivity projects match your saved collection.",
      time: "Today",
    },
  ],
}

type ProjectSeed = Omit<Project, "thumbnailPath" | "sourceLinks">

const createSourceLinks = (slug: string) => [
  { label: "Live demo", href: `https://example.com/projects/${slug}` },
  { label: "Source code", href: `https://github.com/example/${slug}` },
  { label: "Docs", href: `https://docs.example.com/${slug}` },
]

const projectSeeds: ProjectSeed[] = [
  {
    slug: "prompt-harbor",
    title: "Prompt Harbor",
    creatorName: "Zara Khan",
    creatorUsername: "zara-khan",
    category: "AI",
    duration: "6:14",
    views: "162K",
    likes: "26.1K",
    comments: "408",
    publishedAt: "Yesterday",
    description: "A prompt workspace for product teams to organize reusable AI prompts and launch notes.",
    tags: ["LLM", "Prompting", "Workflow"],
    status: "Featured",
    difficulty: "Intermediate",
    developmentStage: "Public beta",
    upvotes: "26.1K",
    bookmarks: "5.4K",
  },
  {
    slug: "model-pilot",
    title: "Model Pilot",
    creatorName: "Owen Hart",
    creatorUsername: "owen-hart",
    category: "AI",
    duration: "7:02",
    views: "148K",
    likes: "22.8K",
    comments: "361",
    publishedAt: "2 days ago",
    description: "An AI experiment dashboard for comparing model outputs, latency, and quality.",
    tags: ["Eval", "Testing", "Analytics"],
    status: "Trending",
    difficulty: "Advanced",
    developmentStage: "Beta",
    upvotes: "22.8K",
    bookmarks: "4.7K",
  },
  {
    slug: "insight-loop",
    title: "Insight Loop",
    creatorName: "Noah Patel",
    creatorUsername: "noah-patel",
    category: "AI",
    duration: "5:49",
    views: "139K",
    likes: "20.4K",
    comments: "298",
    publishedAt: "3 days ago",
    description: "A research summarizer that turns meeting transcripts into shareable AI briefs.",
    tags: ["Summaries", "Research", "Notes"],
    status: "Popular",
    difficulty: "Intermediate",
    developmentStage: "Released",
    upvotes: "20.4K",
    bookmarks: "4.1K",
  },
  {
    slug: "synth-desk",
    title: "Synth Desk",
    creatorName: "Maya Singh",
    creatorUsername: "maya-singh",
    category: "AI",
    duration: "8:11",
    views: "176K",
    likes: "28.9K",
    comments: "422",
    publishedAt: "Yesterday",
    description: "A polished AI command center for generating launch copy, responses, and briefs.",
    tags: ["Automation", "Copy", "Workspace"],
    status: "Featured",
    difficulty: "Advanced",
    developmentStage: "Public preview",
    upvotes: "28.9K",
    bookmarks: "6.2K",
  },
  {
    slug: "context-forge",
    title: "Context Forge",
    creatorName: "Luis Moreno",
    creatorUsername: "luis-moreno",
    category: "AI",
    duration: "6:21",
    views: "104K",
    likes: "15.7K",
    comments: "205",
    publishedAt: "5 days ago",
    description: "A prompt context builder for packaging notes, files, and tasks into one AI payload.",
    tags: ["Context", "Workflow", "Dev tools"],
    status: "Curated",
    difficulty: "Intermediate",
    developmentStage: "MVP",
    upvotes: "15.7K",
    bookmarks: "3.5K",
  },
  {
    slug: "scout-gpt",
    title: "Scout GPT",
    creatorName: "Priya Nair",
    creatorUsername: "priya-nair",
    category: "AI",
    duration: "4:58",
    views: "91K",
    likes: "12.9K",
    comments: "184",
    publishedAt: "6 days ago",
    description: "An AI scout that ranks ideas, opportunities, and launch angles from a short brief.",
    tags: ["Ideation", "Ranking", "Product"],
    status: "Trending",
    difficulty: "Beginner",
    developmentStage: "Prototype",
    upvotes: "12.9K",
    bookmarks: "2.8K",
  },
  {
    slug: "signal-ai",
    title: "Signal AI",
    creatorName: "Elena Park",
    creatorUsername: "elena-park",
    category: "AI",
    duration: "5:36",
    views: "87K",
    likes: "11.8K",
    comments: "176",
    publishedAt: "4 days ago",
    description: "A lightweight AI assistant for surfacing actionable patterns in product research.",
    tags: ["Insights", "Research", "Assistant"],
    status: "Popular",
    difficulty: "Intermediate",
    developmentStage: "Beta",
    upvotes: "11.8K",
    bookmarks: "2.3K",
  },
  {
    slug: "brief-bot",
    title: "Brief Bot",
    creatorName: "Ari Chen",
    creatorUsername: "ari-chen",
    category: "AI",
    duration: "3:51",
    views: "76K",
    likes: "9.4K",
    comments: "139",
    publishedAt: "1 week ago",
    description: "A quick brief generator for kickoff docs, campaign plans, and scoping notes.",
    tags: ["Briefs", "Scoping", "Marketing"],
    status: "New",
    difficulty: "Beginner",
    developmentStage: "MVP",
    upvotes: "9.4K",
    bookmarks: "1.9K",
  },
  {
    slug: "studio-grid",
    title: "Studio Grid",
    creatorName: "Maya Singh",
    creatorUsername: "maya-singh",
    category: "Web",
    duration: "4:44",
    views: "119K",
    likes: "17.6K",
    comments: "241",
    publishedAt: "2 days ago",
    description: "A responsive web studio homepage with sharp spacing and modular sections.",
    tags: ["Responsive", "Landing page", "Grid"],
    status: "Trending",
    difficulty: "Intermediate",
    developmentStage: "Released",
    upvotes: "17.6K",
    bookmarks: "3.8K",
  },
  {
    slug: "landing-forge",
    title: "Landing Forge",
    creatorName: "Ari Chen",
    creatorUsername: "ari-chen",
    category: "Web",
    duration: "5:13",
    views: "102K",
    likes: "14.1K",
    comments: "198",
    publishedAt: "3 days ago",
    description: "A launch page system with editorial pacing and clear CTA hierarchy.",
    tags: ["Marketing", "CTA", "Content"],
    status: "Featured",
    difficulty: "Intermediate",
    developmentStage: "Public beta",
    upvotes: "14.1K",
    bookmarks: "3K",
  },
  {
    slug: "motion-shell",
    title: "Motion Shell",
    creatorName: "Lina Gomez",
    creatorUsername: "lina-gomez",
    category: "Web",
    duration: "5:38",
    views: "95K",
    likes: "13.2K",
    comments: "164",
    publishedAt: "5 days ago",
    description: "A motion-led portfolio website with layered transitions and bold storytelling.",
    tags: ["Motion", "Portfolio", "Animation"],
    status: "Curated",
    difficulty: "Advanced",
    developmentStage: "Beta",
    upvotes: "13.2K",
    bookmarks: "2.7K",
  },
  {
    slug: "pagecraft",
    title: "Pagecraft",
    creatorName: "Owen Hart",
    creatorUsername: "owen-hart",
    category: "Web",
    duration: "6:07",
    views: "88K",
    likes: "11.7K",
    comments: "142",
    publishedAt: "6 days ago",
    description: "A content-first website builder for creating crisp product pages quickly.",
    tags: ["Builder", "CMS", "Publish"],
    status: "Popular",
    difficulty: "Intermediate",
    developmentStage: "Released",
    upvotes: "11.7K",
    bookmarks: "2.4K",
  },
  {
    slug: "orbit-ui",
    title: "Orbit UI",
    creatorName: "Samir Ali",
    creatorUsername: "samir-ali",
    category: "Web",
    duration: "4:29",
    views: "77K",
    likes: "9.8K",
    comments: "108",
    publishedAt: "1 week ago",
    description: "A polished component showcase for modern product websites and docs.",
    tags: ["Components", "Docs", "Library"],
    status: "Trending",
    difficulty: "Beginner",
    developmentStage: "MVP",
    upvotes: "9.8K",
    bookmarks: "2K",
  },
  {
    slug: "carbon-layout",
    title: "Carbon Layout",
    creatorName: "Noah Patel",
    creatorUsername: "noah-patel",
    category: "Web",
    duration: "5:26",
    views: "124K",
    likes: "18.9K",
    comments: "267",
    publishedAt: "Yesterday",
    description: "A dense but readable product layout for SaaS dashboards and admin panels.",
    tags: ["SaaS", "Dashboard", "Layout"],
    status: "Featured",
    difficulty: "Intermediate",
    developmentStage: "Public preview",
    upvotes: "18.9K",
    bookmarks: "4.5K",
  },
  {
    slug: "prism-web",
    title: "Prism Web",
    creatorName: "Luis Moreno",
    creatorUsername: "luis-moreno",
    category: "Web",
    duration: "3:58",
    views: "69K",
    likes: "8.6K",
    comments: "91",
    publishedAt: "4 days ago",
    description: "A clean brochure site with sharp contrast, typography, and subtle motion.",
    tags: ["Brochure", "Typography", "Brand"],
    status: "New",
    difficulty: "Beginner",
    developmentStage: "Prototype",
    upvotes: "8.6K",
    bookmarks: "1.6K",
  },
  {
    slug: "pocket-pulse",
    title: "Pocket Pulse",
    creatorName: "Priya Nair",
    creatorUsername: "priya-nair",
    category: "Mobile",
    duration: "4:17",
    views: "98K",
    likes: "12.8K",
    comments: "177",
    publishedAt: "2 days ago",
    description: "A mobile dashboard for quick status checks, alerts, and on-the-go decisions.",
    tags: ["iOS", "Android", "Notifications"],
    status: "Trending",
    difficulty: "Intermediate",
    developmentStage: "Beta",
    upvotes: "12.8K",
    bookmarks: "2.9K",
  },
  {
    slug: "swipe-studio",
    title: "Swipe Studio",
    creatorName: "Lina Gomez",
    creatorUsername: "lina-gomez",
    category: "Mobile",
    duration: "5:02",
    views: "84K",
    likes: "10.5K",
    comments: "132",
    publishedAt: "5 days ago",
    description: "A mobile-first presentation app for slick product demos and stories.",
    tags: ["Mobile UI", "Presentation", "Motion"],
    status: "Popular",
    difficulty: "Advanced",
    developmentStage: "Public beta",
    upvotes: "10.5K",
    bookmarks: "2.1K",
  },
  {
    slug: "trail-app",
    title: "Trail App",
    creatorName: "Maya Singh",
    creatorUsername: "maya-singh",
    category: "Mobile",
    duration: "6:03",
    views: "91K",
    likes: "11.9K",
    comments: "149",
    publishedAt: "3 days ago",
    description: "A travel companion app that surfaces routes, notes, and offline plans.",
    tags: ["Travel", "Offline", "Maps"],
    status: "Curated",
    difficulty: "Intermediate",
    developmentStage: "Released",
    upvotes: "11.9K",
    bookmarks: "2.4K",
  },
  {
    slug: "habit-loop",
    title: "Habit Loop",
    creatorName: "Noah Patel",
    creatorUsername: "noah-patel",
    category: "Mobile",
    duration: "3:49",
    views: "73K",
    likes: "9.1K",
    comments: "104",
    publishedAt: "1 week ago",
    description: "A habit tracker with gentle nudges, streaks, and quick daily check-ins.",
    tags: ["Habits", "Streaks", "Wellness"],
    status: "New",
    difficulty: "Beginner",
    developmentStage: "MVP",
    upvotes: "9.1K",
    bookmarks: "1.7K",
  },
  {
    slug: "field-notes-mobile",
    title: "Field Notes Mobile",
    creatorName: "Elena Park",
    creatorUsername: "elena-park",
    category: "Mobile",
    duration: "4:36",
    views: "82K",
    likes: "10.8K",
    comments: "126",
    publishedAt: "4 days ago",
    description: "A quick-capture app for observations, sketches, and research notes.",
    tags: ["Notes", "Capture", "Research"],
    status: "Featured",
    difficulty: "Intermediate",
    developmentStage: "Beta",
    upvotes: "10.8K",
    bookmarks: "2.2K",
  },
  {
    slug: "sprint-pocket",
    title: "Sprint Pocket",
    creatorName: "Owen Hart",
    creatorUsername: "owen-hart",
    category: "Mobile",
    duration: "5:21",
    views: "79K",
    likes: "10.1K",
    comments: "111",
    publishedAt: "6 days ago",
    description: "A lightweight mobile sprint board for backlog triage and status updates.",
    tags: ["Tasks", "Teams", "Planning"],
    status: "Trending",
    difficulty: "Intermediate",
    developmentStage: "Public preview",
    upvotes: "10.1K",
    bookmarks: "2K",
  },
  {
    slug: "atlas-mobile",
    title: "Atlas Mobile",
    creatorName: "Zara Khan",
    creatorUsername: "zara-khan",
    category: "Mobile",
    duration: "6:18",
    views: "105K",
    likes: "14.4K",
    comments: "173",
    publishedAt: "Yesterday",
    description: "A mobile operations map for teams who need fast access to signals and blockers.",
    tags: ["Ops", "Monitoring", "Mobile"],
    status: "Popular",
    difficulty: "Advanced",
    developmentStage: "Released",
    upvotes: "14.4K",
    bookmarks: "3.1K",
  },
  {
    slug: "lesson-loom",
    title: "Lesson Loom",
    creatorName: "Elena Park",
    creatorUsername: "elena-park",
    category: "Education",
    duration: "5:07",
    views: "89K",
    likes: "12.2K",
    comments: "148",
    publishedAt: "3 days ago",
    description: "A lesson planning tool for educators building structured learning paths.",
    tags: ["Curriculum", "Planning", "Lessons"],
    status: "Featured",
    difficulty: "Intermediate",
    developmentStage: "Beta",
    upvotes: "12.2K",
    bookmarks: "2.5K",
  },
  {
    slug: "course-canvas",
    title: "Course Canvas",
    creatorName: "Ari Chen",
    creatorUsername: "ari-chen",
    category: "Education",
    duration: "4:51",
    views: "74K",
    likes: "9.6K",
    comments: "117",
    publishedAt: "5 days ago",
    description: "A course builder for outlining modules, assessments, and student goals.",
    tags: ["Courses", "Modules", "Teaching"],
    status: "Curated",
    difficulty: "Beginner",
    developmentStage: "MVP",
    upvotes: "9.6K",
    bookmarks: "1.9K",
  },
  {
    slug: "study-stack",
    title: "Study Stack",
    creatorName: "Samir Ali",
    creatorUsername: "samir-ali",
    category: "Education",
    duration: "6:26",
    views: "81K",
    likes: "10.9K",
    comments: "124",
    publishedAt: "2 days ago",
    description: "A study planner with spaced repetition cues and session tracking.",
    tags: ["Study", "Memory", "Planner"],
    status: "Popular",
    difficulty: "Intermediate",
    developmentStage: "Released",
    upvotes: "10.9K",
    bookmarks: "2.1K",
  },
  {
    slug: "mentor-mode",
    title: "Mentor Mode",
    creatorName: "Maya Singh",
    creatorUsername: "maya-singh",
    category: "Education",
    duration: "5:45",
    views: "68K",
    likes: "8.7K",
    comments: "96",
    publishedAt: "1 week ago",
    description: "A mentoring workspace for feedback, goals, and session summaries.",
    tags: ["Mentorship", "Feedback", "Goals"],
    status: "Trending",
    difficulty: "Beginner",
    developmentStage: "Public preview",
    upvotes: "8.7K",
    bookmarks: "1.6K",
  },
  {
    slug: "quiz-kit",
    title: "Quiz Kit",
    creatorName: "Luis Moreno",
    creatorUsername: "luis-moreno",
    category: "Education",
    duration: "4:23",
    views: "77K",
    likes: "9.8K",
    comments: "103",
    publishedAt: "4 days ago",
    description: "A quiz builder for educators, trainers, and onboarding teams.",
    tags: ["Quizzes", "Assessments", "Forms"],
    status: "New",
    difficulty: "Intermediate",
    developmentStage: "Beta",
    upvotes: "9.8K",
    bookmarks: "2K",
  },
  {
    slug: "classroom-flow",
    title: "Classroom Flow",
    creatorName: "Noah Patel",
    creatorUsername: "noah-patel",
    category: "Education",
    duration: "6:05",
    views: "84K",
    likes: "10.6K",
    comments: "121",
    publishedAt: "6 days ago",
    description: "A classroom operating system for assignments, attendance, and announcements.",
    tags: ["Classroom", "Assignments", "Admin"],
    status: "Featured",
    difficulty: "Intermediate",
    developmentStage: "Released",
    upvotes: "10.6K",
    bookmarks: "2.1K",
  },
  {
    slug: "lab-guide",
    title: "Lab Guide",
    creatorName: "Priya Nair",
    creatorUsername: "priya-nair",
    category: "Education",
    duration: "3:57",
    views: "72K",
    likes: "8.9K",
    comments: "98",
    publishedAt: "Yesterday",
    description: "A guided lab companion for technical workshops and hands-on demos.",
    tags: ["Workshops", "Guides", "Teaching"],
    status: "Curated",
    difficulty: "Beginner",
    developmentStage: "Prototype",
    upvotes: "8.9K",
    bookmarks: "1.8K",
  },
  {
    slug: "signal-stack",
    title: "Signal Stack",
    creatorName: "Owen Hart",
    creatorUsername: "owen-hart",
    category: "Developer Tools",
    duration: "7:48",
    views: "92K",
    likes: "11.2K",
    comments: "181",
    publishedAt: "5 days ago",
    description: "A command palette for shipping faster with analytics, alerts, and CI insights.",
    tags: ["Dashboard", "Metrics", "Productivity"],
    status: "Popular",
    difficulty: "Advanced",
    developmentStage: "Released",
    upvotes: "11.2K",
    bookmarks: "2.6K",
  },
  {
    slug: "schema-guard",
    title: "Schema Guard",
    creatorName: "Samir Ali",
    creatorUsername: "samir-ali",
    category: "Developer Tools",
    duration: "5:34",
    views: "81K",
    likes: "10.4K",
    comments: "136",
    publishedAt: "3 days ago",
    description: "A schema validator for catching API drift before it hits production.",
    tags: ["API", "Validation", "Testing"],
    status: "Trending",
    difficulty: "Intermediate",
    developmentStage: "Beta",
    upvotes: "10.4K",
    bookmarks: "2.2K",
  },
  {
    slug: "build-relay",
    title: "Build Relay",
    creatorName: "Luis Moreno",
    creatorUsername: "luis-moreno",
    category: "Developer Tools",
    duration: "6:11",
    views: "73K",
    likes: "9.5K",
    comments: "119",
    publishedAt: "6 days ago",
    description: "A build monitor that surfaces broken pipelines and release blockers quickly.",
    tags: ["CI", "Builds", "Monitoring"],
    status: "Curated",
    difficulty: "Intermediate",
    developmentStage: "Public preview",
    upvotes: "9.5K",
    bookmarks: "2K",
  },
  {
    slug: "commit-compass",
    title: "Commit Compass",
    creatorName: "Noah Patel",
    creatorUsername: "noah-patel",
    category: "Developer Tools",
    duration: "4:45",
    views: "69K",
    likes: "8.8K",
    comments: "97",
    publishedAt: "Yesterday",
    description: "A release note helper that groups commits into readable changelog entries.",
    tags: ["Git", "Changelog", "Release"],
    status: "New",
    difficulty: "Beginner",
    developmentStage: "MVP",
    upvotes: "8.8K",
    bookmarks: "1.7K",
  },
  {
    slug: "log-lantern",
    title: "Log Lantern",
    creatorName: "Maya Singh",
    creatorUsername: "maya-singh",
    category: "Developer Tools",
    duration: "5:58",
    views: "76K",
    likes: "9.9K",
    comments: "123",
    publishedAt: "4 days ago",
    description: "A log explorer for filtering noisy traces into a clear incident timeline.",
    tags: ["Logs", "Debugging", "Observability"],
    status: "Featured",
    difficulty: "Intermediate",
    developmentStage: "Released",
    upvotes: "9.9K",
    bookmarks: "2.1K",
  },
  {
    slug: "branch-beacon",
    title: "Branch Beacon",
    creatorName: "Priya Nair",
    creatorUsername: "priya-nair",
    category: "Developer Tools",
    duration: "3:46",
    views: "64K",
    likes: "7.6K",
    comments: "83",
    publishedAt: "1 week ago",
    description: "A branch tracker that keeps teams aligned on active work and ownership.",
    tags: ["Git", "Team", "Workflow"],
    status: "Trending",
    difficulty: "Beginner",
    developmentStage: "Prototype",
    upvotes: "7.6K",
    bookmarks: "1.4K",
  },
  {
    slug: "trace-rail",
    title: "Trace Rail",
    creatorName: "Zara Khan",
    creatorUsername: "zara-khan",
    category: "Developer Tools",
    duration: "6:33",
    views: "88K",
    likes: "10.7K",
    comments: "130",
    publishedAt: "2 days ago",
    description: "A tracing dashboard for following requests across services and endpoints.",
    tags: ["Tracing", "APM", "Services"],
    status: "Popular",
    difficulty: "Advanced",
    developmentStage: "Beta",
    upvotes: "10.7K",
    bookmarks: "2.4K",
  },
  {
    slug: "open-lens",
    title: "Open Lens",
    creatorName: "Samir Ali",
    creatorUsername: "samir-ali",
    category: "Open Source",
    duration: "5:12",
    views: "97K",
    likes: "13.4K",
    comments: "164",
    publishedAt: "3 days ago",
    description: "An open-source design viewer for browsing community-built UI patterns.",
    tags: ["MIT", "Components", "Community"],
    status: "Featured",
    difficulty: "Intermediate",
    developmentStage: "Released",
    upvotes: "13.4K",
    bookmarks: "3K",
  },
  {
    slug: "patchwork",
    title: "Patchwork",
    creatorName: "Luis Moreno",
    creatorUsername: "luis-moreno",
    category: "Open Source",
    duration: "6:09",
    views: "83K",
    likes: "10.8K",
    comments: "147",
    publishedAt: "5 days ago",
    description: "A contributor-friendly starter kit for remixing and shipping open source apps.",
    tags: ["Starter", "OSS", "Templates"],
    status: "Trending",
    difficulty: "Intermediate",
    developmentStage: "Public beta",
    upvotes: "10.8K",
    bookmarks: "2.2K",
  },
  {
    slug: "forkline",
    title: "Forkline",
    creatorName: "Owen Hart",
    creatorUsername: "owen-hart",
    category: "Open Source",
    duration: "4:55",
    views: "72K",
    likes: "9.2K",
    comments: "102",
    publishedAt: "1 week ago",
    description: "A collaborative fork management tool for maintaining clean upstream syncs.",
    tags: ["Git", "Repo", "Collaboration"],
    status: "Popular",
    difficulty: "Beginner",
    developmentStage: "MVP",
    upvotes: "9.2K",
    bookmarks: "1.8K",
  },
  {
    slug: "delta-kit",
    title: "Delta Kit",
    creatorName: "Maya Singh",
    creatorUsername: "maya-singh",
    category: "Open Source",
    duration: "5:27",
    views: "79K",
    likes: "10.1K",
    comments: "118",
    publishedAt: "4 days ago",
    description: "An open-source component kit with opinionated defaults and solid docs.",
    tags: ["UI kit", "Docs", "React"],
    status: "Curated",
    difficulty: "Intermediate",
    developmentStage: "Released",
    upvotes: "10.1K",
    bookmarks: "2K",
  },
  {
    slug: "public-path",
    title: "Public Path",
    creatorName: "Elena Park",
    creatorUsername: "elena-park",
    category: "Open Source",
    duration: "3:43",
    views: "66K",
    likes: "8.4K",
    comments: "89",
    publishedAt: "6 days ago",
    description: "A community roadmap board for projects that need transparent planning.",
    tags: ["Roadmap", "Community", "Planning"],
    status: "New",
    difficulty: "Beginner",
    developmentStage: "Prototype",
    upvotes: "8.4K",
    bookmarks: "1.5K",
  },
  {
    slug: "repo-bloom",
    title: "Repo Bloom",
    creatorName: "Ari Chen",
    creatorUsername: "ari-chen",
    category: "Open Source",
    duration: "5:41",
    views: "75K",
    likes: "9.7K",
    comments: "111",
    publishedAt: "Yesterday",
    description: "A contribution-focused repo homepage that makes onboarding feel welcoming.",
    tags: ["Onboarding", "Docs", "GitHub"],
    status: "Featured",
    difficulty: "Intermediate",
    developmentStage: "Beta",
    upvotes: "9.7K",
    bookmarks: "2.1K",
  },
  {
    slug: "clear-cache",
    title: "Clear Cache",
    creatorName: "Noah Patel",
    creatorUsername: "noah-patel",
    category: "Open Source",
    duration: "4:28",
    views: "61K",
    likes: "7.9K",
    comments: "82",
    publishedAt: "2 weeks ago",
    description: "A utility-focused project for cleaning local state, caches, and stale files.",
    tags: ["Utility", "Cleanup", "CLI"],
    status: "Trending",
    difficulty: "Beginner",
    developmentStage: "Public preview",
    upvotes: "7.9K",
    bookmarks: "1.3K",
  },
  {
    slug: "focus-deck",
    title: "Focus Deck",
    creatorName: "Noah Patel",
    creatorUsername: "noah-patel",
    category: "Productivity",
    duration: "4:39",
    views: "120K",
    likes: "16.3K",
    comments: "213",
    publishedAt: "Yesterday",
    description: "A personal planning deck for turning daily goals into a clean execution flow.",
    tags: ["Planning", "Tasks", "Goals"],
    status: "Featured",
    difficulty: "Beginner",
    developmentStage: "Released",
    upvotes: "16.3K",
    bookmarks: "3.6K",
  },
  {
    slug: "task-tide",
    title: "Task Tide",
    creatorName: "Priya Nair",
    creatorUsername: "priya-nair",
    category: "Productivity",
    duration: "5:16",
    views: "98K",
    likes: "12.7K",
    comments: "154",
    publishedAt: "3 days ago",
    description: "A task flow app that keeps priorities, notes, and due dates in sync.",
    tags: ["Tasks", "Due dates", "Flow"],
    status: "Trending",
    difficulty: "Intermediate",
    developmentStage: "Public beta",
    upvotes: "12.7K",
    bookmarks: "2.8K",
  },
  {
    slug: "flow-shelf",
    title: "Flow Shelf",
    creatorName: "Maya Singh",
    creatorUsername: "maya-singh",
    category: "Productivity",
    duration: "6:01",
    views: "86K",
    likes: "10.9K",
    comments: "128",
    publishedAt: "5 days ago",
    description: "A shelf for organizing daily work, references, and launch prep in one place.",
    tags: ["Workspace", "Planning", "References"],
    status: "Curated",
    difficulty: "Intermediate",
    developmentStage: "MVP",
    upvotes: "10.9K",
    bookmarks: "2.1K",
  },
  {
    slug: "daily-relay",
    title: "Daily Relay",
    creatorName: "Elena Park",
    creatorUsername: "elena-park",
    category: "Productivity",
    duration: "3:59",
    views: "70K",
    likes: "8.5K",
    comments: "93",
    publishedAt: "1 week ago",
    description: "A morning check-in tool for habits, priorities, and quick status updates.",
    tags: ["Daily", "Check-ins", "Habits"],
    status: "New",
    difficulty: "Beginner",
    developmentStage: "Prototype",
    upvotes: "8.5K",
    bookmarks: "1.5K",
  },
  {
    slug: "note-harbor",
    title: "Note Harbor",
    creatorName: "Lina Gomez",
    creatorUsername: "lina-gomez",
    category: "Productivity",
    duration: "4:47",
    views: "79K",
    likes: "10.1K",
    comments: "117",
    publishedAt: "4 days ago",
    description: "A compact notes workspace for fast capture, tagging, and recall.",
    tags: ["Notes", "Capture", "Tags"],
    status: "Popular",
    difficulty: "Intermediate",
    developmentStage: "Released",
    upvotes: "10.1K",
    bookmarks: "2.2K",
  },
  {
    slug: "tempo-stack",
    title: "Tempo Stack",
    creatorName: "Luis Moreno",
    creatorUsername: "luis-moreno",
    category: "Productivity",
    duration: "5:29",
    views: "74K",
    likes: "9.4K",
    comments: "101",
    publishedAt: "2 days ago",
    description: "A productivity stack for scheduling work blocks and review windows.",
    tags: ["Timeboxing", "Scheduling", "Focus"],
    status: "Featured",
    difficulty: "Intermediate",
    developmentStage: "Beta",
    upvotes: "9.4K",
    bookmarks: "1.9K",
  },
  {
    slug: "workline",
    title: "Workline",
    creatorName: "Zara Khan",
    creatorUsername: "zara-khan",
    category: "Productivity",
    duration: "6:08",
    views: "93K",
    likes: "12.1K",
    comments: "139",
    publishedAt: "Yesterday",
    description: "A streamlined workline for planning tasks, syncing notes, and keeping momentum.",
    tags: ["Momentum", "Tasks", "Planning"],
    status: "Trending",
    difficulty: "Advanced",
    developmentStage: "Public preview",
    upvotes: "12.1K",
    bookmarks: "2.7K",
  },
]

export const mockProjects: Project[] = projectSeeds.map((project) => ({
  ...project,
  thumbnailPath: `/mock-projects/${project.slug}.jpg`,
  sourceLinks: createSourceLinks(project.slug),
}))

export const mockCreators: Creator[] = [
  {
    username: "maya-singh",
    name: "Maya Singh",
    title: "Product designer",
    bio: "Builds polished interfaces for launch pages, component libraries, and creator tools.",
    projects: 7,
    followers: "128K",
    specialty: "Design systems",
    joinedAt: "March 2022",
    totalUpvotes: "184K",
    socials: [
      { label: "Website", href: "https://example.com/maya-singh" },
      { label: "X", href: "https://x.com/maya-singh" },
      { label: "Dribbble", href: "https://dribbble.com/maya-singh" },
    ],
  },
  {
    username: "owen-hart",
    name: "Owen Hart",
    title: "Frontend engineer",
    bio: "Ships dashboards and developer tooling with clean motion and strong information density.",
    projects: 5,
    followers: "94K",
    specialty: "Dev tools",
    joinedAt: "September 2021",
    totalUpvotes: "132K",
    socials: [
      { label: "Website", href: "https://example.com/owen-hart" },
      { label: "X", href: "https://x.com/owen-hart" },
      { label: "GitHub", href: "https://github.com/owen-hart" },
    ],
  },
  {
    username: "lina-gomez",
    name: "Lina Gomez",
    title: "Creative technologist",
    bio: "Explores motion-led product storytelling and high-contrast editorial layouts.",
    projects: 3,
    followers: "76K",
    specialty: "Motion",
    joinedAt: "January 2023",
    totalUpvotes: "98K",
    socials: [
      { label: "Website", href: "https://example.com/lina-gomez" },
      { label: "X", href: "https://x.com/lina-gomez" },
      { label: "Behance", href: "https://behance.net/lina-gomez" },
    ],
  },
  {
    username: "noah-patel",
    name: "Noah Patel",
    title: "Founder",
    bio: "Publishes operator-grade dashboards and systems for teams that move fast.",
    projects: 7,
    followers: "103K",
    specialty: "Dashboards",
    joinedAt: "June 2022",
    totalUpvotes: "156K",
    socials: [
      { label: "Website", href: "https://example.com/noah-patel" },
      { label: "X", href: "https://x.com/noah-patel" },
      { label: "LinkedIn", href: "https://linkedin.com/in/noah-patel" },
    ],
  },
  {
    username: "ari-chen",
    name: "Ari Chen",
    title: "Brand developer",
    bio: "Creates launch experiences with strong typographic rhythm and clear narrative flow.",
    projects: 4,
    followers: "61K",
    specialty: "Landing pages",
    joinedAt: "May 2022",
    totalUpvotes: "87K",
    socials: [
      { label: "Website", href: "https://example.com/ari-chen" },
      { label: "X", href: "https://x.com/ari-chen" },
      { label: "Instagram", href: "https://instagram.com/ari-chen" },
    ],
  },
  {
    username: "zara-khan",
    name: "Zara Khan",
    title: "AI product designer",
    bio: "Designs AI-first workflows that stay legible, useful, and fast to adopt.",
    projects: 4,
    followers: "112K",
    specialty: "AI tools",
    joinedAt: "February 2022",
    totalUpvotes: "141K",
    socials: [
      { label: "Website", href: "https://example.com/zara-khan" },
      { label: "X", href: "https://x.com/zara-khan" },
      { label: "GitHub", href: "https://github.com/zara-khan" },
    ],
  },
  {
    username: "elena-park",
    name: "Elena Park",
    title: "Learning experience designer",
    bio: "Builds educational products with strong pacing, clarity, and learner feedback loops.",
    projects: 5,
    followers: "88K",
    specialty: "Education",
    joinedAt: "August 2021",
    totalUpvotes: "119K",
    socials: [
      { label: "Website", href: "https://example.com/elena-park" },
      { label: "X", href: "https://x.com/elena-park" },
      { label: "LinkedIn", href: "https://linkedin.com/in/elena-park" },
    ],
  },
  {
    username: "samir-ali",
    name: "Samir Ali",
    title: "Open source maintainer",
    bio: "Maintains reusable systems and community-driven developer tooling.",
    projects: 4,
    followers: "96K",
    specialty: "Open Source",
    joinedAt: "November 2020",
    totalUpvotes: "127K",
    socials: [
      { label: "Website", href: "https://example.com/samir-ali" },
      { label: "X", href: "https://x.com/samir-ali" },
      { label: "GitHub", href: "https://github.com/samir-ali" },
    ],
  },
  {
    username: "priya-nair",
    name: "Priya Nair",
    title: "Product engineer",
    bio: "Ships mobile and productivity tools that feel focused, quick, and easy to return to.",
    projects: 5,
    followers: "101K",
    specialty: "Productivity",
    joinedAt: "April 2022",
    totalUpvotes: "133K",
    socials: [
      { label: "Website", href: "https://example.com/priya-nair" },
      { label: "X", href: "https://x.com/priya-nair" },
      { label: "GitHub", href: "https://github.com/priya-nair" },
    ],
  },
  {
    username: "luis-moreno",
    name: "Luis Moreno",
    title: "Developer advocate",
    bio: "Creates tools and launch-ready products for builders who care about clarity.",
    projects: 6,
    followers: "79K",
    specialty: "Developer tools",
    joinedAt: "May 2021",
    totalUpvotes: "105K",
    socials: [
      { label: "Website", href: "https://example.com/luis-moreno" },
      { label: "X", href: "https://x.com/luis-moreno" },
      { label: "GitHub", href: "https://github.com/luis-moreno" },
    ],
  },
]

export function getProjectBySlug(slug: string) {
  return mockProjects.find((project) => project.slug === slug)
}

export function getCreatorByUsername(username: string) {
  return mockCreators.find((creator) => creator.username === username)
}

export function getProjectsBySlugs(slugs: string[]) {
  return slugs
    .map((slug) => getProjectBySlug(slug))
    .filter((project): project is Project => Boolean(project))
}